### ISSUE TITLE
Add Bitrate Encoding

### ISSUE THREAD

**Issue by vus7294** [moisesmcardona/rav1e_gui#1]
This Tool, Assisted AV1 Encoder that Faster than x265, Now Only Supports Quantizer Encoding. I Tried, 77mb AVC.mp4 was going to AV1 with 400mb AV1.webm with Quantizer 30 and MAX Speed. what?
I Found Quantizer Encoding is Totally Useless to Reduce Size without Losing Quality. I Use Only Bitrate Encoding that is Much Smaller Encoding.
I Hope Bitrate Encoding will add for rav1e Gui. Can You?

**Comment by moisespr123** [comment]
Bitrate encoding is currently not supported by rav1e. Currently, to produce a small size, you should use a high quantizer setting, but of course, the higher the number, the less quality it will have.

Once rav1e supports bitrate encoding, it will be added to the GUI.

**Comment by moisespr123** [comment]
I added bitrate encoding today in the source code, as rav1e got support for it. However, it is failing to encode right now. Probably a rav1e bug.

**Comment by moisespr123** [comment]
Bitrate encoding added in v1.9, however, it is still recommended to use the quantizer mode due to artifacts in the first few frames.
