### ISSUE TITLE
Final merged file is not produced

### ISSUE THREAD

**Issue by Manuel5cc** [moisesmcardona/rav1e_gui#10]
As it seems, the software does all the encoding process but it doesn't produce the final merged file (whatever mkv or webm) and deletes all the temporary files.

**Comment by moisespr123** [comment]
Hmm, strange. What version of ffmpeg are you using? Nightly? Custom ffmpeg build using [media-autobuild-suite](https://github.com/jb-alvarado/media-autobuild_suite)?

**Comment by Manuel5cc** [comment]
The GUI itself says "N-86723-g3b3501f". It was installed via Chocolatey

**Comment by moisespr123** [comment]
I see. What encoding parameters are you using? Can you also try to use [Zeranoe's nightly ffmpeg builds?](https://ffmpeg.zeranoe.com/builds/) rav1e GUI v1.12 was tested and it should be working fine.

**Comment by Manuel5cc** [comment]
I am using the default parameters, didn't touch anything.

**Comment by moisespr123** [comment]
Does the temporary path has any ```'```in it?

**Comment by Manuel5cc** [comment]
Nope it is the root of a hard disk.

**Comment by moisespr123** [comment]
Hmm, can you try creating a folder, something like `C:\temp`?

**Comment by Manuel5cc** [comment]
It's just C:\

**Comment by moisespr123** [comment]
> It's just C:\

This could be the problem. Try making a folder like `C:\temp`

**Comment by Manuel5cc** [comment]
> > It's just C:\
> 
> This could be the problem. Try making a folder like `C:\temp`

I tried this and didn't work either. It is quite rare since I can see the files referenced in my "recent files" section on Windows but they appear as 0 byte files. 
![image](https://user-images.githubusercontent.com/21358555/57234646-69a28100-7021-11e9-8616-e18bb02ce409.png)

**Comment by moisespr123** [comment]
Have you tried using the ffmpeg nightly builds?

**Comment by Manuel5cc** [comment]
> Have you tried using the ffmpeg nightly builds?

I don't really have the knowledge to compile it from scratch but any guides or references would be appreciated :)

**Comment by moisespr123** [comment]
The link for the instructions to get the nightly builds is under the Dependencies section of the Readme. Here's the link: https://moisescardona.me/downloading-ffmpeg-rav1e-gui/

**Comment by Manuel5cc** [comment]
> The link for the instructions to get the nightly builds is under the Dependencies section of the Readme. Here's the link: https://moisescardona.me/downloading-ffmpeg-rav1e-gui/

Oh okay! Apparently this one worked!

**Comment by moisespr123** [comment]
Glad that it worked :)
