### ISSUE TITLE
Gui becomes highly unresponsive for jobs with many threads

### ISSUE THREAD

**Issue by LittleVulpix** [moisesmcardona/rav1e_gui#11]
The gui becomes very unresponsive for jobs with many threads, especially when encoding something longer. If you manage to somehow pause progress, the gui behaves normally again (until resumed). I can also see that the memory usage of the gui jumps to ~400-600MB and then goes back to 200MB every few seconds, so I'm guessing it has to do with logs.

Logs appear very slowly, sort of like... as if it were reading a long logfile, comparing it to something and then only posting the last line.

If I can provide more information, let me know.

It's Windows 10 x64, 32 threads, 20 second pieces, ~2.5h long content.

**Comment by moisespr123** [comment]
Hi,

Are you using the default logging or do you have the "Show PSNR metrics in log" enabled?

I can see why it's slow. The software redirects all of the output to the Rich Text Box component. Unfortunately, this adds a slowdown especially on large encoding tasks. I'll add more options to the GUI and see if they can improve the performance.

**Comment by LittleVulpix** [comment]
I have the PSNR metrics option enabled, I like seeing the numbers :D And yeah, it gets very slow eventually causing the gui to become completely unresponsive. I generally just kill it and restart it since it's "clever" enough to let me resume from where it left off (well, minus in-progress parts, but that's okay).

**Comment by moisespr123** [comment]
In v1.13, the `Clear Log` button is enabled which can be used to clear the output. This should fix the slowdown.
