### ISSUE TITLE
Invalid Argument

### ISSUE THREAD

**Issue by ProFire** [moisesmcardona/rav1e_gui#13]
I'm running version 1.0.2722 of rav1e and the encoder returns this error:
Found argument '-p' which wasn't expected, or isn't valid in this context

**Comment by moisespr123** [comment]
Thanks. I'll take a look into this. I haven't used rav1e in a while, so
possibly some arguments changes.

-Moises

**Comment by moisespr123** [comment]
Ok, found it. The `-p` argument was changed with `--first-pass` and `--second-pass`. I'll work n implementing these changes ASAP.

**Comment by moisespr123** [comment]
Fixed in v1.13: https://github.com/moisesmcardona/rav1e_gui/releases/tag/v1.13
