### ISSUE TITLE
error: 'Unspecified' isn't a valid value for '--range <PIXEL_RANGE>'

### ISSUE THREAD

**Issue by ProFire** [moisesmcardona/rav1e_gui#14]
The latest gui isn't compatible with the latest rav1e build at time of writing this issue.
Error message is:
error: 'Unspecified' isn't a valid value for '--range <PIXEL_RANGE>'

P.S. Good work, by the way!

**Comment by moisespr123** [comment]
Hi,

Thanks for reporting.

It seems the default option is now `Limited`. I'll fix it this afternoon. In the meantime, you can go to `Advanced Settings` and change Pixel Range to `Limited` and it should work.

-Moises

**Comment by moisespr123** [comment]
Fixed in v1.15: https://github.com/moisesmcardona/rav1e_gui/releases/tag/v1.15
