### ISSUE TITLE
Resume operation if files are present

### ISSUE THREAD

**Issue by linearray** [moisesmcardona/rav1e_gui#8]
Sadly this morning my machine crashed and the 16 hour job it was running was wasted.

A simple way to resume an incomplete job could look like this:
Since the input file is split into many parts, it ought to be possible to walk the list of split input files and check which ones do not have output files yet. Since output files can be incomplete, a simple solution would be to just delete the last `threads` output files. This would still save almost all output files and hence the largest share of the job.

Of course it could also be done by continuously tracking which files are done and persisting this information. This could also be combined with a pause/resume button, which would also be great but is a separate feature.

What do you think?

**Comment by moisespr123** [comment]
Hi! Nice ideas. I'll investigate this further

**Comment by moisespr123** [comment]
I'm testing the resume from last session code.

**Comment by moisespr123** [comment]
Also testing the pause/resume button

**Comment by moisespr123** [comment]
Hi, please try v1.8 which I've just released. It adds your suggestions 😁

**Comment by linearray** [comment]
Wow, this is great! And implemented so quickly.

The only suggestion I have is to show some info about the previous session in the resume session dialog that is displayed on application start. The user may have forgotten all about their previous encode and has no idea what is going on.

Right now it says `The temporary folder contains temporary files from a previous session. Do you want to continue the previous encoding session?`, it could say
```
The temporary folder

$TEMPPATH

contains temporary files from the encoding session for

$OUTPUTFILE.

Do you want to continue this encoding session?
```

But that's really just a suggestion. If you want I can make a pull request, so I don't just make work for you.

The pause/resume button works fine in my tests. I'll be sure to recommend rav1e_gui to all my friends :)

**Comment by moisespr123** [comment]
Yes, that sound like a better, more informative message. Also feel free to open another issue regarding this improvement!
